### ISSUE TITLE
June @2nd Review Checklist

### ISSUE THREAD

**Issue by bmarika** [MasterFacilityList/mfl_web#72]
@owagaantony 
- [x] Simple Search (Home Page):
    - [x] One has to double click in order to be allowed to enter a search term; Fix that
    - [x] Fix the instant results styling
    - [x] The search box should me made better
- [x] Remove double click to focus search input
- [x] Rating to reflect changes made

@jason-wanjohi @ngash 
- [x] GIS
    - [x] Bring the GIS loading page to under 500ms
    - [x] Investigate the behaviour of the overlays in GIS
    - [x] Remove the drag  in the facilities drill down page
- [x] Facilities search page use slimmed-down payload
- [x] Facilities summary being called twice
- [x] Remove extra CSS

@liyocee @owagaantony 
- [x] Advanced Search
    - [x] Fix auto focus
    - [x] Add filter by owners 
    - [x] If one selects a ward from the GIS drill down page when one goes to the advanced search page,
        the ward constituency and ward county should be pre-selected
    - [x] When one clicks the facilities link on the navigation menu, the advanced search filters should reset
    - [x] Optimize loading of all facilities page (Advanced search page)
    - [x] Fix animations (mostly in check-boxes) 

@owagaantony 
- [x] Facility Rating
    - [x] Investigate why when a facility is rated, the rating sometimes appears as 0
    - [x] Show the total number of ratings done. e.g 100

@jason-wanjohi 
- [x] Ensure there is fallback plan for old/unsupported browsers
    - [x] Have logos for the 4 main browsers.
    - [x] The logos should link to a browser's official download page
- [x] Stop calling Kenya boundary, host code
- [x] Remove drag from from map
- [x] Styling in map view Navigation

@ngash 
- [x] Improve Overall Performance
    - [x] Sprite images
- [x] Find out why Chrome Header sending 

- [x] Fix OAUTH issues
- [x] Deployment
   - [x] Optimize Nginx
    - [x] Enforce Nginx listens for HTTPS only (Do not turn on the Django HTTPS for development's sake)

@liyocee 
 - [x] Only show published and non-classified facilities

**Comment by ngurenyaga** [comment]
@jason-wanjohi will handle spriting and deployment issues?

On Tue, Jun 2, 2015 at 2:25 PM, Brian Marika <notifications@github.com>
wrote:

> @owagaantony <https://github.com/owagaantony>
>
>    -  Simple Search (Home Page):
>       -  One has to double click in order to be allowed to enter a search
>       term; Fix that
>       -  Fix the instant results styling
>       -  The search box should me made better
>
> @jason-wanjohi <https://github.com/jason-wanjohi>
>
>    -  GIS
>       -  Bring the GIS loading page to under 500ms
>       -  Investigate the behaviour of the overlays in GIS
>       -  Remove the drag even in the facilities drill down page
>
> @liyocee <https://github.com/liyocee>
>
>    -  Advanced Search
>       -  Fix auto focus
>       -  Add filter by owners
>       -  If one selects a ward from the GIS drill down page when one goes
>       to the advanced search page, the ward constituency and ward county should
>       be pre selected
>       -  When one clicks the facilities link on the navigation menu, the
>       filters should be reset
>       -  Optimize loading of all facilities page(Advanced search page)
>
> @owagaantony <https://github.com/owagaantony>
>
>    -  Facility Rating
>       -  Investigate why when a facility is rated, the rating sometimes
>       appears as 0
>       -  Show the total number of ratings done. e.g 100
>
> @jason-wanjohi <https://github.com/jason-wanjohi>
>
>    -  Ensure there is fallback plan for old/unsupported browsers
>       -  Have logos for the 4 main browsers.
>       -  The logos should link to a browser's official download page
>
> @ngash <https://github.com/ngash>
>
>    -  Fix OAUTH issues
>
> @jason-wanjohi <https://github.com/jason-wanjohi>
>
>    -
>
>    Improve Overall Performance
>     -  Sprite images
>     -
>
>    Deployment
>     -  Optimize Nginx
>       -  Enforce Nginx listens for HTTPS only (Do not turn on the Django
>       HTTPS for development's sake)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MasterFacilityList/mfl_web/issues/72>.
>



-- 
Founder & CTO,
Savannah Informatics Limited

No. 11A, off Kabarnet Road

Cellphone: +254-723-002959

ngure.nyaga@savannahinformatics.com
@ngurenyaga

**Comment by bmarika** [comment]
@ngurenyaga  Fixed the assignment issue.
