### ISSUE TITLE
Final public web checklist

### ISSUE THREAD

**Issue by ngurenyaga** [MasterFacilityList/mfl_web#8]
- [x] Simple search 
 - [x] Advanced search / faceting
 - [x] Direct link to faceting in main nav
 - [x] GIS: Country Map
    - [x] Drill down to counties
    - [x] Link to faceting page
    - [x] Opt in: Overlay facilities layer
 - [x] GIS: County Map
    - [x] Drill down to constituencies
    - [x] Link to faceting page
    - [x] Opt in: Overlay facilities layer
 - [x] GIS: Constituency Map
    - [x] Drill down to wards
    - [x] Link to faceting page
    - [x] Opt in: Overlay facilities layer
 - [x] GIS: Ward Map
    - [x] Link to faceting page
    - [x] Opt in: Overlay facilities layer
 - [ ] Facility detail view
    - [x] Print stylesheet for facility detail view
- [x] Facility rating ( requires sign-in, sign-in pop up displayed just in time )
- [x] Contacting the help desk: see https://github.com/MasterFacilityList/mfl_web/issues/4
- [ ] Acceptable behaviour on outdated browsers: was https://github.com/MasterFacilityList/mfl_web/issues/5
- [ ] Fix OAuth issue ( should not need refresh on first login ): was #20 
- [ ] The faceting page should make one call to populate all dropdowns, and the data returned from that custom back-end view should be "just enough" ( names and ids only )
- [x] No overlaying of facilities on map at the ward level

@jason-wanjohi
- [x]  maintain navigation during drill down
- [x] fix heat map showing or not showing
- [ ] training materials:- make screen cast (Kilonzi to give input)

@liyocee 
- [ ] wiring up filtering optimization implemented in the backend 
- [ ] add filter bay all week
- [ ] add filter by owner
